### ISSUE TITLE
Failure during compute: Error in "Read faultyelemdata": CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by priyankasingh** [wilicc/gpu-burn#1]
Hi Wili, I have used the gpu burn to do stress test on my 2 GPUs. The Tesla K40m failed and showed the following errors. After the system stops running is shows the message "Killing process" and hangs without killing the process. I waited 20 minutes but it never stops and gives me the final summary.

I am not sure what it means and why the script is crashing. I hope you can show some light on it.

I have added all the information below.

Thanks.

-------------------------------------------------------------------------------------------------------------------
OS: Centos 7.4
Cuda toolkit version: 9.0
Nvidia driver: 390.30
GCC version: 4.8.5
GPUs: Tesla K40m and Quadro M4000
--------------------------------------------------------------------------------------------------------------------------------------
$ make && ./gpu_burn -d 1200

GPU 0: Tesla K40m (UUID: GPU-660d987e-5b28-3bf6-2a2d-1d5ecae7f6df)
GPU 1: Quadro M4000 (UUID: GPU-ad447a04-f6f5-3ccf-c0f7-3218b1919de2)
Initialized device 1 with 11441 MB of memory (11330 MB available, using 10197 MB of it), using DOUBLES
Initialized device 0 with 8126 MB of memory (8016 MB available, using 7214 MB of it), using DOUBLES
10.4%  proc'd: 446 (74 Gflop/s) - 6636 (423 Gflop/s)   errors: 0 - 0   temps: 93 C - 57 C 
    Summary at:   Wed 11 Apr 11:27:59 BST 2018

13.1%  proc'd: 669 (74 Gflop/s) - 6952 (154 Gflop/s)   errors: 0 - 0   temps: 95 C - 58 C Failure during compute: Error in "Read faultyelemdata": CUDA_ERROR_UNKNOWN
20.5%  proc'd: 892 (74 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - -1  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:30:00 BST 2018

30.6%  proc'd: 1561 (74 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C ^[[B~5B
    Summary at:   Wed 11 Apr 11:32:01 BST 2018

40.7%  proc'd: 2007 (74 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:34:02 BST 2018

50.8%  proc'd: 2453 (73 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:36:03 BST 2018

60.8%  proc'd: 2899 (74 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:38:04 BST 2018

70.9%  proc'd: 3568 (73 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:40:05 BST 2018

74.0%  proc'd: 3791 (73 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
	Summary at:   Wed 11 Apr 11:41:05 BST 2018

81.0%  proc'd: 4014 (74 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:42:06 BST 2018

91.1%  proc'd: 4460 (73 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C 
    Summary at:   Wed 11 Apr 11:44:07 BST 2018

100.0%  proc'd: 5129 (73 Gflop/s) - -1 (154 Gflop/s)   errors: 0 - 0  (DIED!)  temps: 95 C - 58 C

$ nvidia-smi # Just before the GPU crashed
Wed Apr 11 11:28:13 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 00000000:02:00.0 Off |                    0 |
| N/A   94C    P0    97W / 235W |  10288MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro M4000        On   | 00000000:03:00.0 Off |                  N/A |
| 52%   58C    P0    63W / 120W |   7310MiB /  8126MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     21593      C   ./gpu_burn                                 10266MiB |
|    1     21590      C   ./gpu_burn                                  7289MiB |
+-----------------------------------------------------------------------------+

**Comment by wilicc** [comment]
It seems to run fine for the first ~2.5 minutes before the first error.  If it is a hardware stability issue, I'm not surprised that the process doesn't die but hangs in a kernel call (ending up in the GPU drivers).
From the looks of it, I would say you have a faulty Tesla card, but I'd take a look at "dmesg" after the crash.  It can usually tell you whether a GPU ended up being disconnected.
BR, Ville

**Comment by priyankasingh** [comment]
Thanks a lot Ville for getting back so quickly. The Tesla card could be faulty or maybe I need to fix the cooling system because it's overheating.
Here's the 'dmesg' output during anf after the crash. 
'''
[74785.660366] pcieport 0000:00:02.0: AER: Corrected error received: id=0010
[74785.660380] pcieport 0000:00:02.0: PCIe Bus Error: severity=Corrected, type=Data Link Layer, id=0010(Transmitter ID)
[74785.660496] pcieport 0000:00:02.0:   device [8086:6f04] error status/mask=00001000/00002000
[74785.660559] pcieport 0000:00:02.0:    [12] Replay Timer Timeout  
[74889.542031] pcieport 0000:00:02.0: AER: Uncorrected (Fatal) error received: id=0010
[74889.542044] pcieport 0000:00:02.0: PCIe Bus Error: severity=Uncorrected (Fatal), type=Transaction Layer, id=0010(Receiver ID)
[74889.542125] pcieport 0000:00:02.0:   device [8086:6f04] error status/mask=00000020/00000000
[74889.542184] pcieport 0000:00:02.0:    [ 5] Surprise Down Error    (First)
[74889.542234] pcieport 0000:00:02.0: broadcast error_detected message
[74889.542239] nvidia 0000:02:00.0: device has no AER-aware driver
[74889.644112] NVRM: GPU at PCI:0000:02:00: GPU-660d987e-5b28-3bf6-2a2d-1d5ecae7f6df
[74889.644132] NVRM: GPU Board Serial Number: 0322716036227
[74889.644138] NVRM: Xid (PCI:0000:02:00): 79, GPU has fallen off the bus.
[74889.644191] NVRM: GPU at 0000:02:00.0 has fallen off the bus.
[74889.644207] NVRM: GPU is on Board 0322716036227.
[74889.644214] NVRM: A GPU crash dump has been created. If possible, please run
NVRM: nvidia-bug-report.sh as root to collect this data before
NVRM: the NVIDIA kernel module is unloaded.
[74890.545455] pcieport 0000:00:02.0: Root Port link has been reset
[74890.545460] pcieport 0000:00:02.0: AER: Device recovery failed

'''

**Comment by wilicc** [comment]
Hi,

Sorry I forgot to reply to this sooner.  But yes, "GPU has fallen off the bus" means that there is a fault with the card.  I would guess that it overheats given that this happens at the fairly high temperature of 95'C.

**Comment by priyankasingh** [comment]
Yes, that was issue. It was overheating because of the faulty cooling system.
Sorry, I didn't update the thread.
