### ISSUE TITLE
Cannot interrupt the process with ctrl-c

### ISSUE THREAD

**Issue by jmakov** [wilicc/gpu-burn#106]
Running `docker run --rm --gpus all -t gpu_burn ./gpu_burn -tc 3600` and pressing ctrl-c doesn't do anything. Would expect to exit the process. `docker stop mycontainerID` works though.

**Comment by daniel-dona** [comment]
Try passing "-i" to the `docker run`. That should make it interactive so stdin is passed to the command running inside the container, including Ctrl-C.
