### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by schererja** [wilicc/gpu-burn#13]
Is this not being updated anymore?  I do notice that some of the forks are more updated than this one, but haven't checked all forks to find which has the most changes.  Would be great if even the readme was updated to say that this project is no longer updated.

**Comment by f84036980** [comment]
There is a new version 1.0
http://wili.cc/blog/entries/gpu-burn/gpu_burn-1.0.tar.gz

**Comment by schererja** [comment]
Thank you so much for that.
