### ISSUE TITLE
Makefile incompatible with cuda 11

### ISSUE THREAD

**Issue by SaintedSheep** [wilicc/gpu-burn#22]
With the new CUDA 11, compute_30 is not recognised anymore, simply replacing it with compute_50 in the Makefile was enough.

```
make
PATH=/home/deployer/bin:/home/deployer/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:.:/usr/bin:/home/deployer/bin:/home/deployer/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games /usr/local/cuda/bin/nvcc -I/usr/local/cuda/include -arch=compute_30 -ptx compare.cu -o compare.ptx
nvcc fatal   : Value 'compute_30' is not defined for option 'gpu-architecture'
Makefile:10: recipe for target 'drv' failed
make: *** [drv] Error 1
```

Edit: I originally had another issue afterwards but that was on me

**Comment by robbocop8** [comment]
Hi SaintedSheep.
Thanks for the info.

I received the following error after i change to compute_50
Would you be able to help me out?

test@test-pc:~$ nvidia-smi
Sat Jul 11 17:01:07 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    On   | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P8    10W / 151W |    184MiB /  8116MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       974      G   /usr/lib/xorg/Xorg                106MiB |
|    0   N/A  N/A      1110      G   /usr/bin/gnome-shell               75MiB |
+-----------------------------------------------------------------------------+
test@test-pc:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

test@test-pc:~$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

test@test-pc:~$ cd gpu-burn

test@test-pc:~/gpu-burn$ make
PATH=/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin$:.:/usr/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin$ /usr/local/cuda/bin/nvcc -I/usr/local/cuda/include -arch=compute_50 -ptx compare.cu -o compare.ptx
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
g++ -O3 -Wno-unused-result -I/usr/local/cuda/include -c gpu_burn-drv.cpp
gpu_burn-drv.cpp: In instantiation of ‘void GPU_Test<T>::compare() [with T = double]’:
gpu_burn-drv.cpp:342:4:   required from ‘void startBurn(int, int, T*, T*, bool, bool) [with T = double]’
gpu_burn-drv.cpp:599:15:   required from ‘void launch(int, bool, bool) [with T = double]’
gpu_burn-drv.cpp:674:55:   required from here
gpu_burn-drv.cpp:269:31: warning: ‘CUresult cuLaunchGridAsync(CUfunction, int, int, CUstream)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuLaunchGridAsync(d_function, SIZE/g_blockSize, SIZE/g_blockSize, 0), "Launch grid");
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12306:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuLaunchGridAsync(CUfunction f, int grid_width, int grid_height, CUstream hStream);
                                    ^~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:269:31: warning: ‘CUresult cuLaunchGridAsync(CUfunction, int, int, CUstream)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuLaunchGridAsync(d_function, SIZE/g_blockSize, SIZE/g_blockSize, 0), "Launch grid");
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12306:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuLaunchGridAsync(CUfunction f, int grid_width, int grid_height, CUstream hStream);
                                    ^~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:269:31: warning: ‘CUresult cuLaunchGridAsync(CUfunction, int, int, CUstream)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuLaunchGridAsync(d_function, SIZE/g_blockSize, SIZE/g_blockSize, 0), "Launch grid");
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12306:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuLaunchGridAsync(CUfunction f, int grid_width, int grid_height, CUstream hStream);
                                    ^~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp: In instantiation of ‘void GPU_Test<T>::compare() [with T = float]’:
gpu_burn-drv.cpp:342:4:   required from ‘void startBurn(int, int, T*, T*, bool, bool) [with T = float]’
gpu_burn-drv.cpp:599:15:   required from ‘void launch(int, bool, bool) [with T = float]’
gpu_burn-drv.cpp:676:54:   required from here
gpu_burn-drv.cpp:269:31: warning: ‘CUresult cuLaunchGridAsync(CUfunction, int, int, CUstream)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuLaunchGridAsync(d_function, SIZE/g_blockSize, SIZE/g_blockSize, 0), "Launch grid");
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12306:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuLaunchGridAsync(CUfunction f, int grid_width, int grid_height, CUstream hStream);
                                    ^~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:269:31: warning: ‘CUresult cuLaunchGridAsync(CUfunction, int, int, CUstream)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuLaunchGridAsync(d_function, SIZE/g_blockSize, SIZE/g_blockSize, 0), "Launch grid");
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12306:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuLaunchGridAsync(CUfunction f, int grid_width, int grid_height, CUstream hStream);
                                    ^~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:269:31: warning: ‘CUresult cuLaunchGridAsync(CUfunction, int, int, CUstream)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuLaunchGridAsync(d_function, SIZE/g_blockSize, SIZE/g_blockSize, 0), "Launch grid");
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12306:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuLaunchGridAsync(CUfunction f, int grid_width, int grid_height, CUstream hStream);
                                    ^~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp: In instantiation of ‘void GPU_Test<T>::initCompareKernel() [with T = double]’:
gpu_burn-drv.cpp:220:20:   required from ‘void GPU_Test<T>::initBuffers(T*, T*) [with T = double]’
gpu_burn-drv.cpp:324:3:   required from ‘void startBurn(int, int, T*, T*, bool, bool) [with T = double]’
gpu_burn-drv.cpp:599:15:   required from ‘void launch(int, bool, bool) [with T = double]’
gpu_burn-drv.cpp:674:55:   required from here
gpu_burn-drv.cpp:259:28: warning: ‘CUresult cuParamSetSize(CUfunction, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetSize(d_function, __alignof(T*) + __alignof(int*) + __alignof(size_t)), "set param size");
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12037:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetSize(CUfunction hfunc, unsigned int numbytes);
                                    ^~~~~~~~~~~~~~
gpu_burn-drv.cpp:259:28: warning: ‘CUresult cuParamSetSize(CUfunction, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetSize(d_function, __alignof(T*) + __alignof(int*) + __alignof(size_t)), "set param size");
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12037:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetSize(CUfunction hfunc, unsigned int numbytes);
                                    ^~~~~~~~~~~~~~
gpu_burn-drv.cpp:259:28: warning: ‘CUresult cuParamSetSize(CUfunction, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetSize(d_function, __alignof(T*) + __alignof(int*) + __alignof(size_t)), "set param size");
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12037:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetSize(CUfunction hfunc, unsigned int numbytes);
                                    ^~~~~~~~~~~~~~
gpu_burn-drv.cpp:260:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, 0, &d_Cdata, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:260:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, 0, &d_Cdata, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:260:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, 0, &d_Cdata, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:261:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*), &d_faultyElemData, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:261:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*), &d_faultyElemData, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:261:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*), &d_faultyElemData, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:262:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*) + __alignof(int*), &d_iters, sizeof(size_t)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:262:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*) + __alignof(int*), &d_iters, sizeof(size_t)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:262:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*) + __alignof(int*), &d_iters, sizeof(size_t)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:264:33: warning: ‘CUresult cuFuncSetBlockShape(CUfunction, int, int, int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuFuncSetBlockShape(d_function, g_blockSize, g_blockSize, 1), "set block size");
              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:11971:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuFuncSetBlockShape(CUfunction hfunc, int x, int y, int z);
                                    ^~~~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:264:33: warning: ‘CUresult cuFuncSetBlockShape(CUfunction, int, int, int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuFuncSetBlockShape(d_function, g_blockSize, g_blockSize, 1), "set block size");
              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:11971:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuFuncSetBlockShape(CUfunction hfunc, int x, int y, int z);
                                    ^~~~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:264:33: warning: ‘CUresult cuFuncSetBlockShape(CUfunction, int, int, int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuFuncSetBlockShape(d_function, g_blockSize, g_blockSize, 1), "set block size");
              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:11971:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuFuncSetBlockShape(CUfunction hfunc, int x, int y, int z);
                                    ^~~~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp: In instantiation of ‘void GPU_Test<T>::initCompareKernel() [with T = float]’:
gpu_burn-drv.cpp:220:20:   required from ‘void GPU_Test<T>::initBuffers(T*, T*) [with T = float]’
gpu_burn-drv.cpp:324:3:   required from ‘void startBurn(int, int, T*, T*, bool, bool) [with T = float]’
gpu_burn-drv.cpp:599:15:   required from ‘void launch(int, bool, bool) [with T = float]’
gpu_burn-drv.cpp:676:54:   required from here
gpu_burn-drv.cpp:259:28: warning: ‘CUresult cuParamSetSize(CUfunction, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetSize(d_function, __alignof(T*) + __alignof(int*) + __alignof(size_t)), "set param size");
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12037:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetSize(CUfunction hfunc, unsigned int numbytes);
                                    ^~~~~~~~~~~~~~
gpu_burn-drv.cpp:259:28: warning: ‘CUresult cuParamSetSize(CUfunction, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetSize(d_function, __alignof(T*) + __alignof(int*) + __alignof(size_t)), "set param size");
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12037:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetSize(CUfunction hfunc, unsigned int numbytes);
                                    ^~~~~~~~~~~~~~
gpu_burn-drv.cpp:259:28: warning: ‘CUresult cuParamSetSize(CUfunction, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetSize(d_function, __alignof(T*) + __alignof(int*) + __alignof(size_t)), "set param size");
              ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12037:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetSize(CUfunction hfunc, unsigned int numbytes);
                                    ^~~~~~~~~~~~~~
gpu_burn-drv.cpp:260:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, 0, &d_Cdata, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:260:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, 0, &d_Cdata, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:260:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, 0, &d_Cdata, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:261:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*), &d_faultyElemData, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:261:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*), &d_faultyElemData, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:261:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*), &d_faultyElemData, sizeof(T*)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:262:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*) + __alignof(int*), &d_iters, sizeof(size_t)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:262:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*) + __alignof(int*), &d_iters, sizeof(size_t)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:262:25: warning: ‘CUresult cuParamSetv(CUfunction, int, void*, unsigned int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuParamSetv(d_function, __alignof(T*) + __alignof(int*), &d_iters, sizeof(size_t)), "set param");
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:12138:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuParamSetv(CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
                                    ^~~~~~~~~~~
gpu_burn-drv.cpp:264:33: warning: ‘CUresult cuFuncSetBlockShape(CUfunction, int, int, int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuFuncSetBlockShape(d_function, g_blockSize, g_blockSize, 1), "set block size");
              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:11971:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuFuncSetBlockShape(CUfunction hfunc, int x, int y, int z);
                                    ^~~~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:264:33: warning: ‘CUresult cuFuncSetBlockShape(CUfunction, int, int, int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuFuncSetBlockShape(d_function, g_blockSize, g_blockSize, 1), "set block size");
              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:11971:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuFuncSetBlockShape(CUfunction hfunc, int x, int y, int z);
                                    ^~~~~~~~~~~~~~~~~~~
gpu_burn-drv.cpp:264:33: warning: ‘CUresult cuFuncSetBlockShape(CUfunction, int, int, int)’ is deprecated [-Wdeprecated-declarations]
   checkError(cuFuncSetBlockShape(d_function, g_blockSize, g_blockSize, 1), "set block size");
              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gpu_burn-drv.cpp:50:0:
/usr/local/cuda/include/cuda.h:11971:36: note: declared here
 __CUDA_DEPRECATED CUresult CUDAAPI cuFuncSetBlockShape(CUfunction hfunc, int x, int y, int z);
                                    ^~~~~~~~~~~~~~~~~~~
g++ -o gpu_burn gpu_burn-drv.o -O3 -lcuda -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -Wl,-rpath=/usr/local/cuda/lib64 -Wl,-rpath=/usr/local/cuda/lib -lcublas -lcudart -o gpu_burn

**Comment by robbocop8** [comment]
in addtion , this is my bashrc.

test@test-pc:~$ nano /home/$USER/.bashrc

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export PATH=/usr/local/cuda-11.0/bin${PATH:+:${PATH}}$

export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64\${LD_LIBRARY_PATH:+:${LD_LIBR$

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it

**Comment by SaintedSheep** [comment]
Can you fix the formatting of your second comment, please?
Apart from that, either I'm blind or you only get deprecated warnings and your make was successfull.

**Comment by neelfirst** [comment]
thx @SaintedSheep , made a PR reflecting your fix: https://github.com/wilicc/gpu-burn/pull/23
