### ISSUE TITLE
how to run on ubuntu?

### ISSUE THREAD

**Issue by chabgood** [wilicc/gpu-burn#4]

**Comment by wilicc** [comment]
1) install ubuntu, cuda packages, and gcc
2) install gpu-burn
3) run according to the samples
Are you having some specific issues?

**Comment by chabgood** [comment]
I would really help if you would post the packages for non linux people.

**Comment by wilicc** [comment]
I was planning on making a USB stick image of this at some point.  That should be easiest for non-Linux-natives.

**Comment by illtellyoulater** [comment]
@wilicc please make it happen, it would be so convenient and gpu-burn could become the de-facto standard for testing second hand/aftermarket GPUs, giving a hard time to those scammers selling partially worn off GPU as a 100% working units.
Also this will increase exposition to many other developers, which could in turn join the project and make it even better!
