### ISSUE TITLE
If I specify 3600, does it last for 1 hour?

### ISSUE THREAD

**Issue by leeyunhome** [wilicc/gpu-burn#42]
Hello,

If I specify 3600, does it last for 1 hour?

When I run it, it seems to turn off after a few minutes.
Please confirm.

Thank you.

**Comment by wilicc** [comment]
Yes, it's in seconds.  If it turns off after a few minutes, it has stumbled upon on error and hopefully has reported what the error was.  BTW, There is a percentage counter the beginning of status progress lines.
