### ISSUE TITLE
Wrong result when error happens after the last progress report

### ISSUE THREAD

**Issue by tothda** [wilicc/gpu-burn#67]
Hello!

First of all I'd like to thank every contributor for their work, gpu burn is a very useful tool for us.

I think we found a bug in the code that prints out the final results. We used the tool to test a machine with 3 GPUs for 90 minutes. I'm attaching the stdout of gpu burn: [20221207_190200_gpu_burn_stdout.zip](https://github.com/wilicc/gpu-burn/files/10206840/20221207_190200_gpu_burn_stdout.zip)

From the output you can see that around the end of the test (at 92.2%) GPU 1 started to produce some errors:

```
92.2%  proc'd: 2710955 (9344 Gflop/s) - 2744965 (9469 Gflop/s) - 2710060 (9341 Gflop/s)   errors: 0 - 0 - 0   temps: 70 C - 70 C - 81 C 
92.2%  proc'd: 2710955 (9344 Gflop/s) - 2744965 (9469 Gflop/s) - 2710060 (9341 Gflop/s)   errors: 0 - 0 - 0   temps: 70 C - 70 C - 81 C 
92.2%  proc'd: 2710955 (9344 Gflop/s) - 2744965 (9469 Gflop/s) - 2710060 (9341 Gflop/s)   errors: 0 - 0 - 0   temps: 70 C - 70 C - 81 C 
92.2%  proc'd: 2710955 (9344 Gflop/s) - 2744965 (9469 Gflop/s) - 2710060 (9341 Gflop/s)   errors: 0 - 0 - 0   temps: 70 C - 70 C - 81 C 
92.2%  proc'd: 2711850 (9347 Gflop/s) - 2744965 (9469 Gflop/s) - 2710060 (9341 Gflop/s)   errors: 1  (WARNING!)- 0 - 0   temps: 70 C - 70 C - 81 C 
92.2%  proc'd: 2711850 (9347 Gflop/s) - 2744965 (9469 Gflop/s) - 2710955 (9347 Gflop/s)   errors: 1  (WARNING!)- 0 - 0   temps: 70 C - 70 C - 81 C 
92.3%  proc'd: 2711850 (9347 Gflop/s) - 2745860 (9459 Gflop/s) - 2710955 (9347 Gflop/s)   errors: 1  (WARNING!)- 0 - 0   temps: 70 C - 70 C - 81 C 
92.3%  proc'd: 2712745 (9341 Gflop/s) - 2745860 (9459 Gflop/s) - 2710955 (9347 Gflop/s)   errors: 1  (WARNING!)- 0 - 0   temps: 70 C - 70 C - 81 C 
92.3%  proc'd: 2712745 (9341 Gflop/s) - 2745860 (9459 Gflop/s) - 2711850 (9343 Gflop/s)   errors: 1  (WARNING!)- 0 - 0   temps: 70 C - 70 C - 81 C 
```

However the final report says:

```
Tested 3 GPUs:
	GPU 0: OK
	GPU 1: OK
	GPU 2: OK
```

The problem is that the `clientFaulty.at(i) = true;` statement is executed only when the intermediate summary reports are printed.

https://github.com/wilicc/gpu-burn/blob/454d1bfbe276d896cebbe30424a2f6d8caaef644/gpu_burn-drv.cpp#L619-L632

Which happens after 10%, 20%, ..., 90% of progress. However, if an error happens **after** 90% of progress - like that happened in our case - then the flag is not set and the final result will be wrong.

**Comment by wilicc** [comment]
What a nice catch!  Thanks, fixed in latest commit.
