### ISSUE TITLE
`Syntax Error near -i` when trying to execute only one GPU

### ISSUE THREAD

**Issue by noslin005** [wilicc/gpu-burn#73]
I wanted to run gpu_burn on a GPU at a time.
The option `-i N` to execute only on GPU N, does not work.
I got a `Syntax error near -i`.

![image](https://user-images.githubusercontent.com/1957756/223726996-e9ca5e9a-2d5f-4e53-9b16-339215fa8c32.png)

**Comment by wilicc** [comment]
Ah, the space isn't accepted between 'i' and '0'.

**Comment by uPaymeiFixit** [comment]
It seems like maybe this shouldn't be closed until at least the documentation is fixed, because the documentation shows an incorrect example. 
 
![image](https://github.com/wilicc/gpu-burn/assets/1683528/5bfd90f1-8ee1-47f8-a5fb-3be8f8d4b913)

**Comment by Liamazing** [comment]
Bump!
