### ISSUE TITLE
tagging releases / TIME parameter

### ISSUE THREAD

**Issue by alexmyczko** [wilicc/gpu-burn#95]
Hi

Would it be possible to tag releases? That would be great for distributing the software in distributions, there is none
yet according to https://repology.org but that is probably related to no release yet at all.

For the TIME parameter, please specify in help outout that it is in seconds.

I will try to package this for Debian, wip http://sid.ethz.ch/debian/gpu-burn/2024/

Note to self, build dependencies with dynamically linked libraries:
```
$ ldd gpu_burn
	linux-vdso.so.1 (0x00007ffdbd3e2000)
	libcuda.so.1 => /lib/x86_64-linux-gnu/libcuda.so.1 (0x00007feb35400000)
	libcublas.so.11 => /usr/local/cuda/lib64/libcublas.so.11 (0x00007feb2f600000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feb2f3d4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feb35319000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feb352f9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feb2f1ab000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feb352f2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feb352ed000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007feb352e8000)
	libcublasLt.so.11 => /usr/local/cuda/lib64/libcublasLt.so.11 (0x00007feb0ac00000)
```

Thanks

**Comment by GaetanLepage** [comment]
> Would it be possible to tag releases?

That would help indeed ! `gpu-burn` has been packaged on nixpkgs, but we have to pick a random commit from the git. It would be more reliable to use git tags/releases.

**Comment by alexmyczko** [comment]
@GaetanLepage indeed I didn't see https://repology.org/project/gpu-burn/versions

**Comment by alexmyczko** [comment]
https://ftp-master.debian.org/new/gpu-burn_0%2Bgit20240115%2Bds-1.html

**Comment by alexmyczko** [comment]
it is in debian now
